name: NSXLBountyHunter
version: 1
api-version: 1.20
main: com.internal.nysxl.NSXLBountyHunter.main
depend: [NysxlUtilities, Vault]
commands:
  BountyHunter:
    description: Opens a GUI with all active Bounties
    usage: /BountyHunter